### ISSUE TITLE
classifier label 

### ISSUE THREAD

**Issue by sixufenfan21** [ryanmadden/decision-tree#7]
in calc_gain function, "classifier = dataset.attributes[attr_index]" is not right ,I think  "classifier = dataset.classifier " is right,because in the last sentence, you regard Attribute values as classifier label

**Comment by ryanmadden** [comment]
The `classifier` in `calc_gain()` is the current attribute we are calculating gain for. The `calc_gain()` function ultimately returns the resulting entropy if we split on this attribute.
